config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks'}
  root to: 'home#index'

  get '/thankyou', to: 'itinerary#thankyou'
  resources :users
  
  resources :main_events  do
    resources :rsvps, only: [:index, :create]
    resources :sub_events do
      resources :assignments  
    end
    resources :guests
  end
  resources :itinerary, only: [:show]
  resource :user, only: [:edit, :update]

end

app/models/main_event.rb
class MainEvent < ActiveRecord::Base
  belongs_to :user
  has_many :sub_events
  has_many :guests
  accepts_nested_attributes_for :guests

  validates_presence_of :user_id, :title, :groom_full_name, :bride_full_name
  validates_numericality_of :user_id, {only_integer: true}
  validates_uniqueness_of :user_id

end

app/controllers/main_events_controller.rb
class MainEventsController < ApplicationController

  before_filter :restrict_main_access?, :except => [:create, :new, :update]

  def show
    #scope main event by current user
    @main_event = MainEvent.find(params[:id])
    # remove and create soonest scope on the subevents model
    @sub_events = SubEvent.where(main_event_id: params[:id]).order(:date).order(:start_time)

    ### Chart Logic ###
    @true_counts = Hash.new(0)
    @false_counts = Hash.new(0)
    @nil_counts = Hash.new(0)
    
    @sub_events.each do |sub_event|
      sub_event.assignments.each do |assignment|
        if assignment.rsvp == "true"
          @true_counts[sub_event.id] += 1
        elsif assignment.rsvp == "false"
          @false_counts[sub_event.id] += 1
        elsif assignment.rsvp == "no_response"
          @nil_counts[sub_event.id] += 1
        end
      end
    end
  end
  
  def new 
    @main_event = MainEvent.new
  end
  
  def edit
    @main_event = MainEvent.find(params[:id])
  end

  def create
    @main_event = MainEvent.new(main_event_params)
    @main_event.user = current_user
    if @main_event.save
      redirect_to main_event_path(@main_event.id)
    else
      render :new
    end
  end

  def update
    # scope by current_user
    @main_event = MainEvent.find(params[:id])
    if @main_event.update_attributes(main_event_params)
      redirect_to main_event_path(@main_event)
    else
      render :edit
    end
  end

  def destroy
    @main_event = MainEvent.find(params[:id])
  end


  protected

  def main_event_params
    params.require(:main_event).permit(
      :title, :image, :link, :description, :start_time, :end_time, :bride_full_name, :groom_full_name, :date
      )
  end
end

app/helpers/main_event_helper.rb
module MainEventHelper
end

app/views/main_events/_form.html.erb
 <%= form_for @main_event do |f| %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.label "Bride's Name" %><br>
    <%= f.text_field "bride_full_name" %>
  </div>
  <div>
    <%= f.label "Groom's Name" %><br>
    <%= f.text_field "groom_full_name" %>
  </div>
  
  <div><%= f.submit "Submit", class: 'button'%></div>
<% end %>
 
</div>

app/views/main_events/edit.html.erb
<div class="row">
  <div class="large-5 columns">
    <h1>Edit Your Event Details</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/main_events/new.html.erb
<div class="row">   
  <div class="large-4 columns"> 
    <h2>Create an Event</h2>
    <%= render 'form' %>
  </div>
</div>
 

app/views/main_events/show.html.erb
<div class="row top"></div>

<div class="row panel">
    <div class="large-9 large-offset-1 columns">
      <h1> <%= @main_event.title %> </h1> 
      <h3> <%= @main_event.description %> </h3>   
    </div> 
    
    <div class="large-2 columns">
    <%= button_to "Edit", edit_main_event_path(@main_event), class: "edit_button button", :method => "get" %>
      
    </div>
</div>

<div class="row">
  <div class="large-2 columns">
  <%= button_to "Add Event", new_main_event_sub_event_path(@main_event), class: "button sidebar", method:"get" %>
 
    <%= button_to "Guest List", main_event_guests_path(@main_event), class: "button sidebar", :method => "get" %>
 
    <%= button_to "RSVP's", main_event_rsvps_path(@main_event), class: "button sidebar", :method => "get" %>
  </div>  
  <div class="large-10 columns">
  <!-- Send count of events to js -->
    <div id="count" style="display:none;" data-count="<%=@sub_events.count%>"></div>
  <!-- List each subevent -->
    <% @sub_events.each_with_index do |sub_event, index| %>
      <div class="row">
        <div class="large-2 columns">
          <h5><%= sub_event.date.to_s(:long) %></h5>
          <h5><%= sub_event.start_time.to_s(:time) %> </h5>
        </div>
        <div class="large-4 columns subEventName">  
          <h4><%= link_to sub_event.title, main_event_sub_event_path(@main_event, sub_event) %></h4>
        </div>
        <div class="large-6 columns">
        
          <!-- if rsvps were sent, render response stats  -->
          <% if @main_event.rsvp_sent %>

            <!-- build chart for each sub_event -->
            <!-- <div id="response_chart_<%#=index%>" style="width:400px; height:40px; padding-top:10px;"></div> -->

            <%= content_tag :div, nil, class:"homeChart", id:"response_chart_"+index.to_s,
              data: {
                nil_count:@nil_counts[sub_event.id],
                true_count:@true_counts[sub_event.id],
                false_count:@false_counts[sub_event.id]
                } do %>

            <%end%>
          
          <%end%>
        </div>
        <hr/>
      </div>
    <% end %>
    </div>
  </div>
</div>