config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks'}
  root to: 'home#index'

  get '/thankyou', to: 'itinerary#thankyou'
  resources :users
  
  resources :main_events  do
    resources :rsvps, only: [:index, :create]
    resources :sub_events do
      resources :assignments  
    end
    resources :guests
  end
  resources :itinerary, only: [:show]
  resource :user, only: [:edit, :update]

end

app/models/sub_event.rb
class SubEvent < ActiveRecord::Base
  belongs_to :main_event
  has_many :assignments, dependent: :destroy
  has_many :guests, through: :assignments

  validates_presence_of :main_event_id, :title, :location, :date, :start_time, :end_time
  validates_numericality_of :main_event_id, { only_integer: true}

  def full_name
    "#{last}, #{first}"
  end

  
end

app/controllers/sub_events_controller.rb
class SubEventsController < ApplicationController
  before_filter :restrict_access?

  def create
    @sub_event = SubEvent.new(sub_event_params)
    @sub_event.main_event_id = params[:main_event_id]
    # @sub_event = current_main_event.sub_events.build(sub_event_params)
    if @sub_event.save 
      #remove
      @main_event = main_event
      # use current_main_event for id
      redirect_to main_event_path(params[:main_event_id])
    else
      render :new
    end
  end

  def new
    # use current_main_event in view
    @main_event = main_event

    @sub_event = SubEvent.new
  end

  def show
    #remove
    @main_event = main_event
    # @sub_event = current_main_event.sub_event.find(params[:id])
    @sub_event = SubEvent.find(params[:id])
    # in view current_main_event.guests
    @assignment = Assignment.new

    ### guest logic ###
    @guests = Guest.where(main_event_id: params[:main_event_id]).order(:last)
    @guestlist = @sub_event.guests.sort_by &:last

    @no_response = Assignment.where(sub_event_id: @sub_event).where(rsvp: "no_response")
    @declined = Assignment.where(sub_event_id: @sub_event).where(rsvp: "false")
    @attending = Assignment.where(sub_event_id: @sub_event).where(rsvp: "true")
  end

  def edit
    @main_event = main_event
    @sub_event = SubEvent.find(params[:id])
  end

  def update
    @main_event = main_event
    @sub_event = SubEvent.find(params[:id])
    if @sub_event.update_attributes(sub_event_params)
      redirect_to main_event_sub_event_path
    else
      render :edit
    end
  end

  def destroy
    @main_event = main_event
    @sub_event = SubEvent.find(params[:id])
    @sub_event.destroy
    redirect_to main_event_path(params[:main_event_id])
  end

  def sorted_guests(assignments)
    sorted_list = []
    assignments.each do |assignment|
      sorted_list << assignment.guest
    end
    sorted_list.sort_by &:last
  end
  helper_method :sorted_guests

  protected

  def sub_event_params
    params.require(:sub_event).permit(
      :title, :location, :description, :date, :start_time, :end_time, :attire
      )
  end

end

app/helpers/sub_event_helper.rb
module SubEventHelper
end

app/views/sub_events/_form.html.erb
<%= form_for [@main_event, @sub_event] do |f| %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "Location" %><br>
    <%= f.text_field "location" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.label "date" %><br>
    <%= f.date_select :date, order: [:day, :month, :year], selected: Date.today %>
  <div>
  <div>
    <%= f.label "start_time" %><br>
    <%= f.time_field "start_time" %>
  </div>
  <div>
    <%= f.label "end_time" %><br>
    <%= f.time_field "end_time" %>
  </div>
  
  <div>
    <%= f.label "Attire" %><br>
    <%= f.text_field "attire" %>
  </div>
  
  <div><%= f.submit "Submit", class: 'button' %></div>
<% end %>

app/views/sub_events/_guest_modal.html.erb
<% @guestlist.each_with_index do |guest, index| %>
    <a href="#" data-reveal-id="guestModal<%=index%>"> <h5><strong><%= guest.last %>, <%= guest.first %></strong></h5></a>
    <div id="guestModal<%=index%>" class="reveal-modal" data-reveal>
     <div class="row">
      <div class="large-4 columns guestName">
        <%= guest.last %>, <%= guest.first %> 
      </div>
      <div class="large-4 columns">
       <%= button_to "Remove from GuestList", main_event_sub_event_assignment_path(@main_event, @sub_event, guest), class: "button",  :method => "delete" %>
      </div>
      <div class="large-4 columns">
        <%= button_to "Full Guest Details", main_event_guest_path(@main_event, guest), class: "button", :method => "get" %>
       <a class="close-reveal-modal">x</a>
      </div>
     </div>
    </div>  

   <hr/>   
<%end%>

app/views/sub_events/_guest_rsvps.html.erb
<% if @attending.count > 0 %>
  <table class="large-4 columns">
    <thead>
      <tr>
        <th style="color: #13B265; text-align:center;">Confirmed Attending</th>
      </tr>
    </thead>
  <% sorted_guests(@attending).each_with_index do|guest, index| %>
    <tbody>
      <tr>
        <td>
          <a href="#" data-reveal-id="attendingGuestModal<%=index%>"><h5><strong><%= guest.last %>, <%= guest.first %></strong></h5></a>
        </td>
      </tr>
          <div id="attendingGuestModal<%=index%>" class="reveal-modal large" data-reveal>
        
         <div class="row">
          <div class="large-4 columns guestName">
            <%= guest.last %>, <%= guest.first %> 
          </div>
          <div class="large-4 columns">
           <%= button_to "Remove from GuestList", main_event_sub_event_assignment_path(@main_event, @sub_event, guest), class: "button",  :method => "delete" %>
          </div>
          <div class="large-4 columns">
            <%= button_to "Full Guest Details", main_event_guest_path(@main_event, guest), class: "button", :method => "get" %>
          </div>
           <a class="close-reveal-modal">x</a>
         </div>
        </div>  
    </tbody>
  <%end%> 
<%end%>
</table> 

<% if @declined.count > 0 %>
  <table class="large-4 columns">
    <thead>
      <tr>
        <th style="color: #B22613; text-align:center;">Regretfully Declined</th>
      </tr>
    </thead>
  <% sorted_guests(@declined).each_with_index do|guest, index| %>
    <tbody>
      <tr>
        <td>
          <a href="#" data-reveal-id="declinedGuestModal<%=index%>"> <h5><strong><%= guest.last %>, <%= guest.first %></strong></h5></a>
        </td>
      </tr>
    <div id="declinedGuestModal<%=index%>" class="reveal-modal large" data-reveal>
     <div class="row">
      <div class="large-4 columns guestName">
        <h2><%= guest.last %>, <%= guest.first %> </h2>
      </div>
      <div class="large-4 columns">
       <%= button_to "Remove from GuestList", main_event_sub_event_assignment_path(@main_event, @sub_event, guest), class: "button",  :method => "delete" %>
      </div>
      <div class="large-4 columns">
        <%= button_to "Full Guest Details", main_event_guest_path(@main_event, guest), class: "button", :method => "get" %>
      </div>
       <a class="close-reveal-modal">x</a>
     </div>
    </div>  
  </tbody>
  <%end%> 
<%end%>
</table>

<% if @no_response.count > 0 %>
  <table class="large-4 columns">
    <thead>
      <tr>
        <th style="color: #8D8DAD; text-align:center;">Unconfirmed</th>
      </tr>
    </thead>
  <% sorted_guests(@no_response).each_with_index do|guest, index| %>
    <tbody>
      <tr>
        <td>
          <a href="#" data-reveal-id="unconfirmedGuestModal<%=index%>"> <h5><strong><%= guest.last %>, <%= guest.first %></strong></h5></a>
        </td>
      </tr>
    <div id="unconfirmedGuestModal<%=index%>" class="reveal-modal large" data-reveal>
     <div class="row">
      <div class="large-4 columns guestName">
        <h2><%= guest.last %>, <%= guest.first %> </h2>
      </div>
      <div class="large-4 columns">
       <%= button_to "Remove from GuestList", main_event_sub_event_assignment_path(@main_event, @sub_event,guest), class: "button",  :method => "delete" %>
      </div>
      <div class="large-4 columns">
        <%= button_to "Full Guest Details", main_event_guest_path(@main_event, guest), class: "button", :method => "get" %>
      </div>
       <a class="close-reveal-modal">x</a>
     </div>
    </div>  
   </tbody>
  <%end%> 
<%end%>
</table>

app/views/sub_events/edit.html.erb
<div class="row">
  <div class="large-6 columns">
    <h2>Edit Your Subevent</h2>
      <%= render 'form' %>
  </div>
</div>

app/views/sub_events/new.html.erb
<div class="row">
  <div class="large-6 columns">
    <h1>Create a SubEvent</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/sub_events/show.html.erb
<div class="row top">

<div class="row panel">
  <div class="large-6 columns">
    <h1><%= @sub_event.title %></h1><br/>
    <h4><%= @sub_event.description %></h4><br/>
    <h4><%= @sub_event.date.to_s(:long) %></h4>
    <h4><%= @sub_event.start_time.to_s(:time) %> to <%= @sub_event.end_time.to_s(:time) %></h4>
    
    <div class="row details">
      <div class="large-5 columns">
        <%= button_to "Edit Event", edit_main_event_sub_event_path(@main_event, @sub_event), class: "panel_button button", method: "get"%>
      </div>
      <div class="large-5 columns">
        <%= button_to "Delete Event", main_event_sub_event_path(@main_event, @sub_event), class: "panel_button button", method: "delete", data: {confirm: "Are you sure you want to delete?"} %>
      </div>
      <div class="large-2 columns"></div>
      </div>
  </div>
  <div class="large-6 columns">
    <!-- if rsvps were sent, render response stats  -->
    <% if @main_event.rsvp_sent %>

      <!-- build chart for each sub_event -->
      <div id="response_chart" style="width:500px; height:400px;"></div>

      <script type="text/javascript" charset="utf-8">
        $(function(){
          $('#response_chart').highcharts({
            chart: {
              backgroundColor: null
            },
            title:{
              text: null
            },
            credits:{
              enabled:false
            },
            series: [{
              type: 'pie',
              data: [ 
                  {name:'No Response', y: <%=@no_response.count%>, color: '#8D8DAD'},
                  {name:'Attending', y: <%=@attending.count%>, color: '#13B265'},
                  {name:'Declined', y: <%=@declined.count%>, color: '#B22613'}
                  ]
             }]
            });
          });
        </script>
    <%end%>
  </div>
</div>

<div class="row guestsPadding">
  <div class="large-9 columns">
    <h3><strong>Guests for this Event</strong></h3>
  </div>

  <!-- Register Guests Button/Modal -->
  <div class="large-3 columns">  
    <a href="#" class= "button" data-reveal-id="myModal">Register Guests</a>
      <div id="myModal" class="reveal-modal tiny" data-reveal>
        <%= form_for [@main_event, @sub_event, @assignment] do |f| %>
          <%= fields_for(@assignment) do |assign| %>
            <%= collection_select(:assignment, :guest_id, @guests, :id, :full_name,  {}, {multiple: true, style:'height:100px'}) %>
          <% end %>
          <%= f.hidden_field :registration_type, value: "from_sub_event_show" %>

          <%= f.submit "Register Guests", class: "button topSpace" %>
        <% end %>
        <a class="close-reveal-modal"></a>
      </div>
  </div>
</div>

<div class="row">
  <!-- List each guest as modal  --> 
  <!-- If RSVP's are sent, render them in categories --> 
  <%if @main_event.rsvp_sent == true%>
    <%= render 'guest_rsvps' %>

  <!-- else, just list each guest currently attending -->
  <%else%>
    <%= render 'guest_modal' %>
  <%end%>
</div>
</div>