config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks'}
  root to: 'home#index'

  get '/thankyou', to: 'itinerary#thankyou'
  resources :users
  
  resources :main_events  do
    resources :rsvps, only: [:index, :create]
    resources :sub_events do
      resources :assignments  
    end
    resources :guests
  end
  resources :itinerary, only: [:show]
  resource :user, only: [:edit, :update]

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  belongs_to :main_event
  has_many :assignment, dependent: :destroy
  has_many :sub_events, through: :assignment

  validates_presence_of :main_event_id, :email, :first, :last 
  validates :email, format: {with: VALID_EMAIL_REGEX }

  def full_name
    "#{last}, #{first}"
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :restrict_access?
    
  def index
    @main_event = main_event
    @guests = @main_event.guests.sort_by &:last
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.main_event_id = params[:main_event_id]
    
    if @guest.save
      @main_event = main_event
      redirect_to main_event_guests_path
    else
      render :new
    end
  end

  def new
    @main_event = main_event
    @guest = Guest.new
    
  end

  def show
    @main_event = main_event
    @guest = Guest.find(params[:id])
    @assignment = Assignment.new
    @assigned_events = @guest.sub_events
    @unassigned_events = SubEvent.where.not(id: @guest.sub_event_ids).where(main_event_id: @main_event)
  end

  def edit
    @main_event = main_event
    @guest = Guest.find(params[:id])
  end

  def update
    @main_event = main_event
    @guest = Guest.find(params[:id])
    if @guest.update_attributes(guest_params)
      redirect_to main_event_guest_path
    else
      render :edit
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to main_event_guests_path
  end

  protected

  def guest_params
    params.require(:guest).permit(
      :email, :first, :last
    )
  end

end

app/helpers/guest_helper.rb
module GuestHelper
end

app/views/guests/_form.html.erb
<%= form_for [@main_event, @guest] do |f| %>
  <div>
    <%= f.label "Email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "First Name" %><br>
    <%= f.text_field "first" %>
  </div>
  <div>
    <%= f.label "Last Name" %><br>
    <%= f.text_field "last" %>
  </div>
  <div><%= f.submit "Submit", class: "button" %></div>
<% end %>

app/views/guests/edit.html.erb
<div class="row">
  <div class="large-5 columns">
    <h2>Edit Guest</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/guests/index.html.erb
<div class="row top"></div>

<div class="row panel">
  <div class="large-9 columns">
    <h1> <%= @main_event.title   %> - Guest List </h1> 
  </div>
  
  <div class="large-3 columns">
  <%= button_to "Add a New Guest", new_main_event_guest_path(@main_event),class: "add_button button", :method => "get" %>
  </div>
</div>

<div class="row">
  <div class="large-8 columns">
    <%  @guests.each do |guest| %>
      <div class="row">
        <div class="large-6 columns">
          <h4> <%= link_to guest.last + ", " + guest.first, main_event_guest_path(@main_event, guest)%></h4>  
          <hr>
        </div>
      </div>    
    <% end %>
  </div>
</div>    

app/views/guests/new.html.erb
<div class="row">
  <div class="large-5 columns">
    <h2>Create New Guest</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/guests/show.html.erb
<div class="row top">

<div class="row panel">
  <div class="large-6 large-offset-1 columns">
    <h1> <%=@guest.first%> <%=@guest.last%></h1>
    <h5> <%=@guest.email%></h5>
  </div>
  <div class="large-5 columns">
  <a href="#" class="add_button button" data-reveal-id="subEventModal">Add Guest to Another Event</a>
    
    <div id="subEventModal" class="reveal-modal small" data-reveal>
      <% @unassigned_events.each do |subEvent| %>
        <div class="row">
          <div class="large-3 columns">
            <%= form_for [@main_event, subEvent, @assignment], html:{ class: "button_to" } do |f| %>
              <%= f.hidden_field :registration_type, :value => "other" %>
              <%= f.hidden_field :guest_id, :value => @guest.id %>
              <%= f.submit "Add", :class => "submit_button button" %>
            <% end %>
          </div>
          <div class="large-2 columns"></div>
          <div class="large-7 columns addGuestModal-name">
            <%= subEvent.title %>
          </div>
        </div>
      <% end %>
    </div>
      
  </div>
</div>


<div class="row">
  <div class="large-6 large-offset-2 columns">
    <h3>Invites for <%= @guest.first %> </h3>
  </div>
</div>  

<div class="row">
  <div class="large-2 columns">
  <%= button_to "Edit Guest", edit_main_event_guest_path, class: "button sidebar", :method => "get" %>

  <%= button_to "Delete Guest", main_event_guest_path, class: "delete_button button sidebar", method: "delete", data: {confirm: "Are you sure you want to delete?"} %>
  </div>

  <div class="large-10 columns listEvents">
    <% @assigned_events.each_with_index do |subEvent, index| %>
      <a href="#" data-reveal-id="subEventModal_2<%=index%>"><h5><%=subEvent.title %></h5></a>
      <div id="subEventModal_2<%=index%>" class="reveal-modal tiny" data-reveal>
        <div class="row">
          <div class="large-10 large-centered columns removeGuestModal">
            <%= button_to "Remove from this Event?", main_event_sub_event_assignment_path(@main_event, subEvent, @guest), class: "center_button button", :method => "delete" %>
          </div>
        </div>
      </div>
      <hr/>
    <% end %>
  </div>
</div>