config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks'}
  root to: 'home#index'

  get '/thankyou', to: 'itinerary#thankyou'
  resources :users
  
  resources :main_events  do
    resources :rsvps, only: [:index, :create]
    resources :sub_events do
      resources :assignments  
    end
    resources :guests
  end
  resources :itinerary, only: [:show]
  resource :user, only: [:edit, :update]

end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.email %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>

<!-- LOGGED IN NAVIGATION BAR -->

  <% if current_user %>
    <div class ="fixed">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1 id= "header-font"><%= link_to "Black Tie", root_path %></a></h1>
          </li>
       
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="has-dropdown">
              <a href="#">Hello, <%= current_user.firstname %></a>
              <ul class="dropdown">
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        </section>
      </nav>
    </div>

  <% end %>

<!-- LOGGED IN NAVIGATION BAR -->   

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "BlackTie" %></title>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.3.6/slick.css"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

     <link href='http://fonts.googleapis.com/css?family=League+Script|Parisienne|Molle:400italic|Marck+Script|Engagement|Satisfy|Rochester|Sacramento|Droid+Sans|Proxima+Nova_Light|Ubuntu|Raleway|Lora|Open Sans|Lato' rel='stylesheet' type='text/css'>

  
    <%= csrf_meta_tags %> 

    <%= render 'layouts/header' unless current_page?(controller: 'home', action: 'index') %>


    <% if current_page?(controller: 'home', action: 'index') %>
      <%= javascript_include_tag "homepage" %>
      <script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.slick/1.3.6/slick.min.js"></script>
    <% else %>
      <%= javascript_include_tag "application" %>
      <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
    <% end %>
  </head>

  <body>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= yield %>
  </body>
</html>